name: Flutter Build Web & APK

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows you to manually trigger the build from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Setup WebAssembly SQLite
        run: dart run sqflite_common_ffi_web:setup

      - name: Configure Web Template
        run: |
          flutter config --enable-web
          flutter create . --platforms web

      - name: Build Web App
        run: flutter build web --release --base-href /smart_campus/

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart_campus_web
          path: build/web/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart_campus_apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: "v1.0.${{ github.run_number }}"
          name: "Release v1.0.${{ github.run_number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
